export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const FETCH_BEGIN   = 'FETCH_PRODUCTS_BEGIN';
export const FETCH_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_FAILURE = 'FETCH_PRODUCTS_FAILURE';